### ISSUE TITLE
assert_equals integer issue

### ISSUE THREAD

**Issue by lukesg08** [pedal-edu/pedal#128]
in the following code:
```python
feedback = assert_equal(call("calculateVolume", 4, 6), 100.31)
```
calculateVolume returns 0, however, this works as a passing test (or at least no feedback is generated). When making calculateVolume return 0.0 instead, this works as intended and provides feedback

**Comment by acbart** [comment]
Never got an email notification about this, but just tested and confirmed that you are absolutely correct! What a bizarre and unfortunate error. It turns out that it's because of how Python's `int` class handles `__sub__` and `__rsub__` magic methods: https://stackoverflow.com/a/54775988/1718155

Basically, since we proxy all of the `call` results (same as `run` and `eval`) in a `SandboxResult` that re-implements all possible magic methods, we need to handle the `int` conversion ourselves. I'll work on this fix!

**Comment by acbart** [comment]
Wow, much trickier to resolve than I initially guessed it would be. Still, I think that this will improve the correctness substantially. Basically, we now fully unpack the values on both sides, try it with the first operator's direction, and then try it the other way. Still requires certain specialized cases (e.g., there is no `str.__radd__`), but I've included a battery of tests (which we are now passing): https://github.com/pedal-edu/pedal/blob/1b7f9619a0a52c680194891890cb923d78c0f0b8/tests/test_sandbox.py#L558

I'm honestly surprised this hasn't come up sooner. I guess the type checker usually stops students from returning an integer from a float function, but that would imply that anything could be happening on my exams..!

Great find, @lukesg08, thanks for reporting!
