### ISSUE TITLE
Data State for BoolType

### ISSUE THREAD

**Issue by lukesg08** [pedal-edu/pedal#23]
```python
set_source("var = 14\n"
           "var = '14'\n"
           "var = False\n")
match = find_match("_var_")
data_state = match['_var_']
data_state = match['_var_'].get_data_state()
print(data_state.type) #UnknownType
print(data_state.trace[0].type)#StrType
print(data_state.trace[0].trace[0].type)#NumType
```
I expected the first print statement to print BoolType instead of UnknownType

**Comment by acbart** [comment]
I can't reproduce this one. Just running it in cpython causes data_state to be None, since you never run `tifa_analysis()` between `set_source` and `get_data_State`. If I add that in, then I get the expected behavior of bool/str/num.

On the BlockPy side, I tried using that student code with the given instructor code, and it also recognized a bool/str/num.

Can you give some more context for this?

**Comment by lukesg08** [comment]
I can't seem to reproduce this problem either...but I swear I had this issue yesterday. And I actually did call tifa_analysis() when I was doing this as I was actually using a self-defined function instead of set_source. So I'm not sure what the issue was or what could have caused it...

```python
def to_source(source):
    MAIN_REPORT.clear()
    set_source(source)
    parse_program()
    tifa_analysis()
```
It was in an interactive console, so I can't produce the exact environment it happened in.
