### ISSUE TITLE
Duplicate Syntax Error Labels

### ISSUE THREAD

**Issue by lukesg08** [pedal-edu/pedal#50]
syntax_error and SyntaxError tags are currently both used. At some point these should be unified.

**Comment by acbart** [comment]
There's the `syntax_error` in the `source` category, and also a `syntax_error` in the `runtime` category. Although they do overlap, I don't think that it's a huge deal - the redundancy between the two systems makes a certain amount of sense (you might use them independently, although BlockPy happens to default to using them both). There was a period in V3 where the Runtime labels were getting placed in accidentally as `CamelCase`, but that is now fixed in the latest version.
