### ISSUE TITLE
Negative feedback __bool_ check?

### ISSUE THREAD

**Issue by acbart** [pedal-edu/pedal#53]
What should the __bool__ of a feedback object return? Currently, it returns `True` if the feedback condition was met. However, arguably, perhaps it should return `False` if the condition was met and the Feedback has negative valence and `True` if it has positive valence.

This would allow you to write things like:

```python
if assert_equal(1+1, 2) and prevent_literal(2):
    set_success()
```

Whereas currently you'd have to invert their logic.

This doesn't really matter for `FeedbackResponse` situations which are unconditional.

**Comment by lukesg08** [comment]
I think the inversion actually makes sense given the current structure. If the condition is met, the feedback object returns true makes sense because we're detecting the presence of a pattern. Instead, I think what might need to change is the names of things like prevent_literal. In the case of that function, it's not "preventing" the literal persay, it's detecting whether there is a literal. So it should actually probably be **has_literal** or **hardcoded** instead of prevent literal. So then the lines of code would make more sense as 
```python
if assert_equal(1+1, 2) and not has_literal(2):
    set_success()
```

or
```python
if assert_equal(1+1, 2) and not hardcoded(2):
    set_success()
```
as opposed to

```python
if assert_equal(1+1, 2) and not prevent_literal(2):
    set_success()
```

**Comment by acbart** [comment]
That's a great idea for `prevent_literal`, but we're backed into a corner with `assert_equal`. That function returns True if the feedback condition is met - in other words, if the student failed to meet the assertion. In other words, I wrote `assert_equal(1+1, 2)` but that produces a False-y value currently! And I'm loathe to change `assert_*` functions because that's the exact thing that other instructors will be expecting to see (heck, I was already considering changing the `prevent_*` and `ensure_*` functions to use the `assert_*` naming scheme!).

**Comment by lukesg08** [comment]
I understand the issue more now that I realize the assert returns True if the student didn't meet the condition of equality. A little bit of rambling. Maybe assertions themselves should be different? In traditional asserts, if the assert fails, it actually throws an exception and stops the program, and presumably gives feedback in the form of the thrown exception. But in theory, should assert_equal really be giving feedback? I think the usage that assertions were made for is different from the goal of feedback functions/objects. They are currently used by instructors to give feedback in that they are familiar and convenient to give feedback, but are ultimately a different type of "thing", where I'm not exactly sure to what "thing" refers. I think the real confounding thing is that assertions weren't really meant for feedback, so the language "assert" doesn't really make sense in the context of feedback.

In the case of a classroom, where I want to know whether a student has failed to write an addition statement for instance, I'm expecting that to return true that they DID do something e.g. if I name a function missing_summation, it would have a negative valence, but I'm expecting that to return True just because of the name of the function.

If we change it so negative valence returns false and positive valence returns true, I feel like that's more logical mental hoops to jump through when people are making their own feedback functions instead of allowing instructors to give their own meaning to what meeting a condition should mean for positive and negative valence feedback objects.

So I think that assertions are, in a way, a special type of "legacy" feedback hack, and should perhaps receive different treatment as opposed to blanketing it onto all negative valence feedback objects.

**Comment by acbart** [comment]
Hm, perhaps you're right that these are orthogonal. Personally, I like the declarative nature of all these statements, both the positive and negative ones. However, there seems to be a real distinction between "whether the condition of the statement was met" and "whether the thing detected was good/bad." So connecting the valence and the condition seems to be a misstep.

I'm wondering whether this might not be as big a deal as I might think, if we decide that #54 might mean "by default, not having negative feedback makes your submission correct". How often do you need to conditionally take an action base on the result of an assertion? The example I have above is for `set_success`... but are there really other cases? And even if they are, they might be very rare - suggesting it'd be okay to occasionally have to write things like `if not assert_equal(call('add', 1, 2), 3)` to check to see if the condition is met.

In fact, thinking about it, if the instructor really wanted to test something like that, why wouldn't they just check that condition directly without invoking an `assert_equal`? There's no reason they can't write `if call('add', 1, 2) == 3`.

I'll probably know better on the other side of updating all the feedback functions, but I feel like the answer for now is just "nah".
